# Build stage**********************************************
FROM node:16.14.0-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

#Production Stage**********************************************
FROM node:16.14.0-alpine

WORKDIR /app

COPY --from=build /app/build /app/build
COPY package.json package-lock.json ./

RUN npm install --production

EXPOSE 7002

CMD ["npm", "start"]